build:
	GOOS=darwin GORACH=arm64 go build -o binaries/go-clipboard-darwin-arm64
	GOOS=darwin GORACH=x64 go build -o binaries/go-clipboard-darwin-x64
	GOOS=linux GORACH=x64 go build -o binaries/go-clipboard-linux-x64
	GOOS=windows GORACH=x64 go build -o binaries/go-clipboard-win32-x64.exe
